"""Emit the P2 certificate as Lean source for the Karanos repo.

Consumes the two verified Python artifacts — the finite-quotient cover
(quotients.search) and the proof-forest certificate DAG (certgraph) — and
writes generated Lean modules that the Karanos development checks:

  Karanos/Generated/Witness.lean      the two witness supports (words)
  Karanos/Generated/Equalities.lean   the 560 product-coincidence certs
  Karanos/Generated/Distinct.lean     the ℤ/42 + S₄ separation data

Every number here is already self-verified on the Python side (free
reduction for equalities, image comparison for distinctness). The Lean
side re-checks from scratch — this codegen only transcribes; it never
becomes a trusted step. Words are emitted as `List Letter` over an
inductive alphabet a/A/b/B, matching the hand-written Karanos core.

This is a TRANSCRIBER, not a prover: it is deliberate that nothing here
imports Lean or asserts anything true. It turns validated data into text.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "engine"))

from karanos_engine.certgraph import CertifiedBallQuotient, Piece  # noqa: E402
from karanos_engine.kaplansky import (  # noqa: E402
    RELATOR_1,
    RELATOR_2,
    WITNESS_NONUP_A,
    WITNESS_NONUP_B,
    parse_word,
)
from karanos_engine.quotients import search  # noqa: E402

_LETTER_CTOR = {0: "Letter.a", 1: "Letter.A", 2: "Letter.b", 3: "Letter.B"}
HEADER = (
    "-- GENERATED by erdos-engine/scripts/p2_codegen.py — do not edit by hand.\n"
    "import Karanos.Core\n\nset_option linter.style.longLine false\n"
    "set_option linter.style.header false\n"
)


def lean_word(word: tuple[int, ...]) -> str:
    return "[" + ", ".join(_LETTER_CTOR[g] for g in word) + "]"


def lean_piece(piece: Piece) -> str:
    conj, ridx, sign = piece
    return f"⟨{lean_word(conj)}, {ridx}, {'true' if sign > 0 else 'false'}⟩"


def emit_witness() -> str:
    a = ",\n  ".join(lean_word(parse_word(w)) for w in WITNESS_NONUP_A)
    b = ",\n  ".join(lean_word(parse_word(w)) for w in WITNESS_NONUP_B)
    return (
        f"{HEADER}\nnamespace Karanos.Generated\n\n"
        f"/-- Side A of the non-unique-product witness (32 words). -/\n"
        f"def witnessA : List (List Letter) := [\n  {a}\n]\n\n"
        f"/-- Side B of the non-unique-product witness (28 words). -/\n"
        f"def witnessB : List (List Letter) := [\n  {b}\n]\n\n"
        f"end Karanos.Generated\n"
    )


def emit_partners(q: CertifiedBallQuotient) -> str:
    """One entry per product pair (u, v) in canonical A-major order: the
    partner words and a direct, Python-re-verified certificate that
    u++v = pu++pv in the free group modulo relators. The canonical order
    makes Lean's coverage check a plain list equality."""
    words_a = [parse_word(w) for w in WITNESS_NONUP_A]
    words_b = [parse_word(w) for w in WITNESS_NONUP_B]
    by_class: dict[int, list[tuple[int, int]]] = {}
    for i, wa in enumerate(words_a):
        for j, wb in enumerate(words_b):
            prod = tuple(list(wa) + list(wb))
            by_class.setdefault(q.class_of_word(prod), []).append((i, j))
    partner: dict[tuple[int, int], tuple[int, int]] = {}
    for members in by_class.values():
        if len(members) < 2:
            raise AssertionError("singleton product class — witness would not be non-u.p.")
        head = members[0]
        for m in members:
            partner[m] = head if m != head else members[1]
    entries: list[str] = []
    n = 0
    for i, wa in enumerate(words_a):
        for j, wb in enumerate(words_b):
            k, m = partner[(i, j)]
            pu, pv = words_a[k], words_b[m]
            assert (k, m) != (i, j) and (pu != wa or pv != wb)
            pieces = q.flat_pieces(tuple(list(wa) + list(wb)), tuple(list(pu) + list(pv)))
            body = ", ".join(lean_piece(p) for p in pieces)
            entries.append(
                f"def pc{n} : PartnerCert :=\n"
                f"  ⟨{lean_word(wa)}, {lean_word(wb)}, {lean_word(pu)}, "
                f"{lean_word(pv)}, [{body}]⟩"
            )
            n += 1
    joined = "\n\n".join(entries)
    index = ", ".join(f"pc{i}" for i in range(n))
    return (
        f"{HEADER}\nnamespace Karanos.Generated\n\n"
        f"{joined}\n\n"
        f"/-- All {n} partner certificates, in canonical A-major order. -/\n"
        f"def partnerCerts : List PartnerCert := [{index}]\n\n"
        f"end Karanos.Generated\n"
    )


def emit_distinct() -> str:
    report = search(verbose=False)
    homs = [c for c in report["cover"] if isinstance(c, dict) and "a" in c]  # type: ignore[union-attr]
    lines = [f"{HEADER}\nnamespace Karanos.Generated\n"]
    lines.append("\n/-- The abelianization ℤ/42 is defined in Karanos.Core; the")
    lines.append("permutation homomorphisms that finish distinctness follow. -/")
    for i, hom in enumerate(homs):
        a = ", ".join(str(x) for x in hom["a"])  # type: ignore[index]
        b = ", ".join(str(x) for x in hom["b"])  # type: ignore[index]
        deg = len(hom["a"])  # type: ignore[arg-type]
        lines.append(
            f"\n/-- Separating homomorphism {i} into S_{deg}. -/\n"
            f"def hom{i} : SepHom := ⟨{deg}, #[{a}], #[{b}]⟩"
        )
    idx = ", ".join(f"hom{i}" for i in range(len(homs)))
    lines.append("\n/-- The permutation homomorphisms covering non-abelian pairs. -/")
    lines.append(f"def sepHoms : List SepHom := [{idx}]\n\nend Karanos.Generated\n")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tree", type=int, default=12)
    ap.add_argument("--close", type=int, default=10)
    ap.add_argument("--out", type=Path, default=Path("Karanos/Generated"))
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    print(f"building certified quotient tree={args.tree} close={args.close} …", flush=True)
    q = CertifiedBallQuotient(2, [RELATOR_1, RELATOR_2], args.tree, args.close)
    assert len(q.ball(4)) == 161 and len(q.ball(6)) == 1311, "anchor failed"

    (args.out / "Witness.lean").write_text(emit_witness())
    eqs = emit_partners(q)
    (args.out / "Equalities.lean").write_text(eqs)
    (args.out / "Distinct.lean").write_text(emit_distinct())
    n_eq = eqs.count("PartnerCert :=")
    print(f"emitted Witness, Equalities ({n_eq} partner certs), Distinct → {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
